### ISSUE TITLE
Update abscissa Cargo.lock to use latest zeroize

### ISSUE THREAD

**Issue by amrali** [iqlusioninc/abscissa#27]
Cargo.lock has zeroize 0.4.0, we need 0.4.2 to include support for musl-libc.

**Comment by tarcieri** [comment]
I think I'd probably prefer to remove `Cargo.lock` from the repo. The reason is this ensures CI always runs against the latest dependencies, which better simulates the experience a user gets when they `cargo update` to pull in the crate for the first time (or install a binary that depends on it vicariously).

**Comment by tarcieri** [comment]
Whoops, never closed this out. Abscissa now uses `zeroize` v0.9
